=== Common type definitions
The following types are used to describe the request and response data
from the server.

==== Error-Object
Describes compiler-errors in Modelica files or Modelica script files.
Gets decoded as `de.thm.mope.compiler.CompilerError` inside the server.
[source,js]
----
{
  "type": "Error" | "Warning", //type of the message from the compiler
  "file": <String>, //absolute path to the file which contains the error
  "start": <File-Position>, //Start-point of error
  "end": <File-Position>, //End-point of error
  "message": <String> //Message from the compiler
}
----

==== FilePath
A path to a file.
Gets decoded as `de.thm.mope.position.FilePath` inside the server.
[source,js]
----
{
  "path": <String> //absolute path to the script
}
----

==== File-Position
Describes a position inside of a file. Contains a line and a column.
Gets decoded as `de.thm.mope.position.FilePosition` inside the server.
[source,js]
----
{
  "line": <number>, //line number
  "column": <number> //column number
}
----

==== FileWithLine
A path to a file and the line containing the searched value.
Gets decoded as `de.thm.mope.position.FileWithLine` inside the server.
[source,js]
----
{
  "path": <String>, //absolute path to the file
  "line": <number> //line number
}
----

==== Suggestion-Object
Describes possible code completions.
Representation is `de.thm.mope.suggestion.Suggestion` inside the server.
[source,js]
----
{
  //kind of completion; 1 of the listed strings
  "kind": "Type" | "Variable" | "Function" | "Keyword" | "Package" | "Model" | "Class" | "Property",
  "name": <String>, //the completion for the given word
  //OPTIONAL: list containing names of parameters if completionType=function
  "parameters": [
    <String>,
    <String>,
    ...
  ],
  //OPTIONAL: the class comment describing the name attribute
  "classComment": <String>,
  //OPTIONAL: the `Modelica-type` of the name
  "type": <String>
}
----

==== TypeOf
The type of a property.
Representation is `de.thm.mope.suggestion.TypeOf` inside the server.
[source,js]
----
{
  "name": <String>, //name of property
  "type": <String>, //type of property
  //OPTIONAL: property's comment
  "comment": <String>
}
----
